export const CHANGE_MENU_STATUS = "CHANGE_MENU_STATUS";
export const CHANGE_ACTIVE_NAV = "CHANGE_ACTIVE_NAV";
export const CHANGE_ACTIVE_SLIDE = "CHANGE_ACTIVE_SLIDE";
export const CHANGE_ACTIVE_HOVER = "CHANGE_ACTIVE_HOVER";
